### ISSUE TITLE
Extract table issue - don't get an underscore

### ISSUE THREAD

**Issue by Crypto49** [BobLd/tabula-sharp#17]
Hi @BobLd,

Many thanks also from me for the helpful library!

I used the _SpreadsheetExtractionAlgorithm_ try to extract tables from a PDF file, a sample attached.

The names from the table are intended to represent variable names for a computer program.

Unfortunately, the result is shown without the underscore:

I get "Content" instead of "C_ontent"

![Example](https://user-images.githubusercontent.com/63670511/117835047-f834e300-b277-11eb-8f97-f44e7fce7937.png)

After `c.SetTextElements(TextElement.MergeWords(page.GetText(c.BoundingBox)));` was called in _SpreadsheetExtractionAlgorithm.cs_, `this.textElements = textElements;` is executed in `public void SetTextElements(List<T> textElements){}` in _RectangularTextContainer.cs_.

I found out that the order is exchanged when assigning values ​​in `this.textElements = textElements;`:

List of values ​​before assignment:

![assigning_1](https://user-images.githubusercontent.com/63670511/117924436-0a556680-b2f6-11eb-82ea-c27c526cee2e.png)

List of values ​​after assignment:

![assigning_2](https://user-images.githubusercontent.com/63670511/117924805-9d8e9c00-b2f6-11eb-9818-e3ab29a05ae5.png)

Later the back part will be cut off, I think.

Unfortunately I haven't found a solution. I would be very grateful for any help.		

[Example PDF.pdf](https://github.com/BobLd/tabula-sharp/files/6459985/Example.PDF.pdf)

**Comment by BobLd** [comment]
Hi @Crypto49, thanks for your feed. I gave your document a try and it appears the problem comes from the `GetText()` function:
https://github.com/BobLd/tabula-sharp/blob/343a387e6052825c7832a1ad6709efaa62f5e52d/Tabula/Cell.cs#L64-L84

It uses the `ILL_DEFINED_ORDER()` sorting scheme that is far from perfect apparently (hence the name 😄, it's taken form the original java library).

Short therm, I would recommend you implement you own `GetText()` function.
On my side, I will need to find a way to give more flexibility with that. One negative aspect I can already spot is that the sorting is done in-place, which is why the order of the character is changed (if you don't use `GetText()`, the order is correct):
```csharp
Utils.Sort(this.textElements, new ILL_DEFINED_ORDER());
```

**Comment by Crypto49** [comment]
Many thanks for finding the cause of the problem.

During the analysis I noticed that the vertical text with an underscore is recognized correctly when `useLineReturns` is false (a sample attached).
In my function, I just left it out.
I'm using the `textElements[].Left` property to reorder the horizontal text.

Granted, I'm not a C # expert, so I overwritten the function as follows:

```C#
        /// <summary>
        /// Gets the cell's text.
        /// </summary>
        /// <param name="useLineReturns"></param>
        public override string GetText(bool useLineReturns)
        {
            if (base.textElements.Count == 0)
            {
                return "";
            }

            StringBuilder sb = new StringBuilder();
            bool textAlignmentHorizontal = this.BoundingBox.Width > this.BoundingBox.Height ? true : false;

            if (textAlignmentHorizontal)
            {
                this.textElements.Sort((a,b) => a.Left.CompareTo(b.Left));
            }

            foreach (TextChunk tc in this.textElements)
            {
                sb.Append(tc.GetText());
            }

            return sb.ToString().Trim();
        }
```
I hope my solution doesn't affect other parts of the program, but for me it works.

Thanks again for your help!

[Example 2.pdf](https://github.com/BobLd/tabula-sharp/files/6494090/Example.2.pdf)

**Comment by ahinin79** [comment]
any good way to implement custom GetText()?
